version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: core-database
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    networks:
      - local
  mongodb:
    image: mongo:latest
    container_name: document-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./dbdatamongo:/data/db

networks:
  local:
    name: local-network