import { Inter, Noto_Color_Emoji } from "next/font/google";
import "./global.css";
import { AuthProviders } from "./core/auth/authProvider";
import SessionGuard from "./core/auth/sessionProvider";

const notoColorEmoji = Noto_Color_Emoji({ weight: "400", subsets: ["emoji"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <AuthProviders>
                    <SessionGuard>{children}</SessionGuard>
                </AuthProviders>
            </body>
        </html>
    );
}
