import { Inter, Noto_Color_Emoji } from 'next/font/google';
import './global.css';

const notoColorEmoji = Noto_Color_Emoji({ weight: "400", subsets: ['emoji'] })
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
