// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService manages the authentication lifecycle for the desktop app.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAccessToken returns the access token, refreshing if necessary.
 */
export function GetAccessToken(): $CancellablePromise<string> {
    return $Call.ByID(3776374147);
}

/**
 * GetUserInfo fetches user profile from Zitadel.
 */
export function GetUserInfo(): $CancellablePromise<$models.UserInfo> {
    return $Call.ByID(3327194123);
}

/**
 * HandleCallback processes the deep link callback from the browser.
 */
export function HandleCallback(callbackURL: string): $CancellablePromise<void> {
    return $Call.ByID(911977689, callbackURL);
}

/**
 * Initialize should be called on application startup.
 */
export function Initialize(cfg: config$0.AppConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3413322022, cfg);
}

/**
 * IsAuthenticated returns true if a valid access token is available.
 */
export function IsAuthenticated(): $CancellablePromise<boolean> {
    return $Call.ByID(1560798419);
}

/**
 * Login initiates the PKCE flow.
 */
export function Login(): $CancellablePromise<void> {
    return $Call.ByID(1110226029);
}

/**
 * Logout actively revokes tokens at Zitadel and clears the keychain.
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(272077654);
}
