// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UserInfo represents the standard OIDC user claims.
 */
export interface UserInfo {
    "sub": string;
    "email": string;
}
