version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: core-database
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    networks:
      - dbnet
    healthcheck:
      test: pg_isready -h localhost -p 5432
      interval: 2s
      timeout: 5s
      retries: 15

networks:
  dbnet:
    name: custom_local_network
