server {
    listen 80;
    server_name power.durgakiran.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name power.durgakiran.com;

    ssl_certificate /etc/nginx/ssl/_wildcard.durgakiran.com.pem;
    ssl_certificate_key /etc/nginx/ssl/_wildcard.durgakiran.com-key.pem;

    client_max_body_size 50M;

    location / {
        proxy_pass http://launchsite:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
