// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService provides methods for the frontend to manage configuration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the current configuration.
 */
export function GetConfig(): $CancellablePromise<$models.AppConfig | null> {
    return $Call.ByID(786993094);
}

/**
 * GetInitialRoute returns the initial deep link route the app was launched with.
 */
export function GetInitialRoute(): $CancellablePromise<string> {
    return $Call.ByID(2807869729);
}

/**
 * SetInitialRoute sets the initial route.
 */
export function SetInitialRoute(route: string): $CancellablePromise<void> {
    return $Call.ByID(3448262213, route);
}
