// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig represents the persistent configuration for the desktop app.
 */
export interface AppConfig {
    "server_url": string;
    "zitadel_url": string;
    "client_id": string;
}
