// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationService provides native OS notifications to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Notify triggers a system notification with the given title and message.
 * It returns an error string (empty if success) so the frontend can catch failures.
 */
export function Notify(title: string, message: string): $CancellablePromise<string> {
    return $Call.ByID(1282019499, title, message);
}
