import React from 'react';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import AddPage from '../addPage';
const createDoc = vi.fn();
vi.mock('@http/hooks', () => ({ usePost: () => [{ data: null, isLoading: false, errors: null }, createDoc] }));
beforeEach(() => vi.clearAllMocks());
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it('creates v2 whiteboards and retries a lost acknowledgement with the same key', async () => {
    const fetcher = vi.fn().mockRejectedValueOnce(new TypeError('Lost acknowledgement')).mockResolvedValueOnce(new Response(JSON.stringify({ data: { pageId: 42, spaceId: 'space-1' } })));
    vi.stubGlobal('fetch', fetcher);
    const editPage = vi.fn();
    render(<AddPage isOpen setIsOpen={() => {}} spaceId="space-1" editPage={editPage} />);
    fireEvent.click(screen.getByRole('button', { name: 'Whiteboard' }));
    fireEvent.change(screen.getByPlaceholderText('Untitled whiteboard'), { target: { value: 'Roadmap' } });
    fireEvent.click(screen.getByRole('button', { name: 'Create' }));
    await screen.findByText('Lost acknowledgement');
    fireEvent.click(screen.getByRole('button', { name: 'Create' }));
    await waitFor(() => expect(editPage).toHaveBeenCalledWith(42));
    expect(fetcher.mock.calls[0][0]).toBe('/api/v2/editor/space/space-1/whiteboard/create');
    expect(JSON.parse(fetcher.mock.calls[0][1].body)).toEqual({ title: 'Roadmap' });
    expect(fetcher.mock.calls[0][1].headers['Idempotency-Key']).toBe(fetcher.mock.calls[1][1].headers['Idempotency-Key']);
    expect(createDoc).not.toHaveBeenCalled();
});
