.PHONY: dev build-mac build-win build-linux

dev:
	wails3 dev

build-mac:
	wails3 build -platform darwin/universal

build-win:
	wails3 build -platform windows/amd64

build-linux:
	wails3 build -platform linux/amd64
